name: adso
channels:
  - conda-forge
dependencies:
  - python>=3.7
  - pathlib
  - numpy
  - dask >= 2021.5
  - dask-ml
  - h5py >= 3.0
  - more-itertools
  - scikit-learn >= 0.22
  - nltk
  - sparse
  - dill
  - pyldavis
  - pandas
  - gensim
  # only conda
  - graph-tool
  - topicmapping
  - mallet
  # pip
  - pip
  - pip:
      - tomotopy
