name: adso
channels:
  - conda-forge
dependencies:
  # python
  - python>=3.6
  # dev dependencies
  - mamba
  - poetry
  - nox
  - black
  - mypy
  - flake8
  - flake8-annotations
  - flake8-black
  - flake8-bugbear
  - flake8-docstrings
  - flake8-import-order
  - darglint
  # project dependencies
  - pathlib
  - numpy
  - dask
  - dask-ml
  - h5py
  - more-itertools
  - scikit-learn
  - nltk
  # pip
  - pip
  - pip:
      # dev
      - flake8-bandit
