name: adso
channels:
  - conda-forge
dependencies:
  # python
  - python>=3.6
  # dev dependencies
  - poetry
  - nox
  - black
  - mypy
  - flake8
  - mamba
  # project dependencies
  - pathlib
  - numpy
  - dask
  - dask-ml
  - h5py
  - more-itertools