name: adso
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - pathlib
  - numpy
  - dask
  - dask-ml
  - h5py >= 3.0
  - more-itertools
  - scikit-learn >= 0.22
  - nltk
  - sparse
  - dill
  - pyldavis
  - pandas
  - gensim >= 4.0
  - mallet >= 2.0.8
