name: Coverage
on: push
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-miniconda@v2
      with:
        python-version: '3.8'
        architecture: x64
        activate-environment: adso
    - run: conda install nox
    - run: nox -s cov
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}